/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import ch.qos.logback.core.net.SyslogOutputStream;
import org.modelmapper.ModelMapper;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

@SpringBootApplication
public class App {


    public static void main(String[] args) {
        SpringApplication.run(App.class);
        System.out.println("RUNNING SPRING APPLICATION");
    }

    @Bean
    public ModelMapper modelMapper(){
        return new ModelMapper();
    }
}
